rename for WETH deployment (#535)
This PR just adds an optional `$name` parameter to the deploy macro so that we can specify a deploy a contract with one name as another.

This is needed to run the orderbook API with ganache, since it tries to get the deployed WETH contract and fails:
```
2021-04-30T11:03:11.667Z ERROR shared::tracing: thread 'main' panicked at 'couldn't load deployed native token: NotFound("5777")', orderbook/src/main.rs:102:10:
thread 'main' panicked at 'couldn't load deployed native token: NotFound("5777")', orderbook/src/main.rs:102:10
```

### Test Plan

The orderbook can start connected to Ganache:
```
$ cargo run -p contracts --bin deploy --features bin
$ cargo run -p orderbook
... # no errors
```