[Trivial] Slightly more practical tenderly link (#575)
Some simulations can contain a lot of calldata (e.g. after merging or when using complex 1Inch routes). This can lead to the tenderly link not working because of 

> Error: URI Too Long

In this case it's usually easy enough to copy the link without the calldata (or just 0x) and manually paste the in the text field. This PR makes it that when doing so the network Id can also be copied (right now it's at the very end after the long blob)

### Test Plan
CI